name: BCV rates

on:
  schedule:
    - cron: '5 * * * *'
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  scrape-and-update:
    runs-on: ubuntu-latest

    environment: main

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run currency scraper
        env:
          BCV_URL: ${{ secrets.BCV_URL }}
          LOCAL_TIMEZONE: ${{ secrets.LOCAL_TIMEZONE }}
          BCV_DATE_SELECTOR: ${{ secrets.BCV_DATE_SELECTOR }}
          BCV_USD_SELECTOR: ${{ secrets.BCV_USD_SELECTOR }}
          BCV_EUR_SELECTOR: ${{ secrets.BCV_EUR_SELECTOR }}
        run: python src/main.py

      - name: Commit and push changes
        if: github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"

          git add data/current.json data/next.json
          git commit -m "automated: update rates values" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
